### ISSUE TITLE
Please use encodeUriComponent when referencing user input in URLs

### ISSUE THREAD

**Issue by philpott** [Socital/GTM-tag-template#2]
https://github.com/Socital/GTM-tag-template/blob/b55c9c180a194cb00f7a470e15573866dfe85e76/template.tpl#L59

Please use [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) when referencing user input in URLs.

**Comment by PhawkesGR** [comment]
@philpott this issue and [https://github.com/Socital/GTM-tag-template/issues/1](this) are fixed now. Do we need to re-submit?

**Comment by philpott** [comment]
No need to resubmit thanks for the fixes.
